### ISSUE TITLE
Import Module comes 12 Errors

### ISSUE THREAD

**Issue by thomasmoawad** [Ruud279b/SnowflakeConnector#1]
Hi SnowflakeConnector maintainers. I'm a big fan of your work and would love to utilize it in my project. I've downloaded the SnowflakeConnector, Encryption Module, and Database Connector Module, into my blank Mendix 9.20.0 project. This results in 12 errors. This makes it a bit difficult to get started.

Can you please share advice on how to resolve these errors? Additionally, a quick start video could be a nice bonus here.

Much appreciated.

Thank you

![Screenshot 2023-11-29 at 2 26 19 PM](https://github.com/RuudFl/SnowflakeConnector/assets/87026657/a9541ce0-1e68-4fc1-b547-ec94b16f3355)

**Comment by RuudFl** [comment]
Hi @thomasmoawad, i published a new release and optimized the module for usage in mx9/mx10 (in combination with the latest Atlas modules), so that layout errors do not occur in projects that use Mendix Atlas.,
