### ISSUE TITLE
Database can only be saved if it is in the database already

### ISSUE THREAD

**Issue by strategicalliances** [Ruud279b/SnowflakeConnector#2]
Hi Ruud,

I am quite certain from a look into the save logic of database profiles, that in your latest version (3.0.0) of the SF connector it is not possible to save a NEW database profile since the database profile is retrieved from the database during saving and returns an error if it is empty. The error is not very descriptive in addition as it refers to the warehouse and not to a database profile that could not be found. In 2.1 my configuration for the database profile can be added.

Best,
Lina

**Comment by RuudFl** [comment]
Hi Lina,

Thanks for raising attention to this bug! It has been fixed an a new release has been uploaded to the Mendix Marketplace.

Regards,
Ruud
